meson.build

The output was named libsane-airscan.so instead of libsane-airscan.so.1

meson: fix soname

---

README.md

The eSCL driver works perfectly fine with
the Epson XP 8600 series.

Update Readme with Epson XP 8600 Series

---

airscan-mdns.c

In case of an error (timeout), addr is NULL and causes a null pointer dereference.

airscan-mdns: fix segmentation fault if event is AVAHI_RESOLVER_FAILURE

---

Makefile

Hi Alex,
I found the issue during packaging sane-airscan for Fedora - Makefile is using hard coded stripping of debug symbols.
This behavior has its usage during normal builds, but OS buildsystems would like to generate a proper debuginfo packages.
The patch makes this settings configurable via STRIP variable e.g. ```make install STRIP=''```.
Would you mind adding it to the project?
Thank you in advance and have a nice day,
Zdenek

Makefile: make stripping configurable

---

Makefile

Hi,
buildsystems add several linking flags depending on OS - Makefile should be capable to pass them to all executables and libraries which are built.
airscan-discover wasn't built with OS buildsystem LDFLAGS, because $(LDFLAGS) is missing from invocation.
Would you mind adding the patch to the project? Please let me know if I should change something.
Thank you in advance,
Zdenek

Makefile: use ldflags for linking airscan-discover too

---

Makefile

In order to satisfy Debian's build lines' checker (blhc), I had to patch these in, to make sure the environment's CFLAGS, CPPFLAGS and LDFLAGS would go everywhere needed.

Allow compilation flag override from Debian's

---

README.md

I ran the the [Installation from pre-build binaries](https://github.com/alexpevzner/sane-airscan#installation-from-pre-build-binaries) steps on Ubuntu 18.04 and then ran
`scanimage -L`
and the output immediately picked up the HP OfficeJet Pro 8020 series scanner.
> device `airscan:e0:HP OfficeJet Pro 8020 series [72CF42]' is a eSCL HP OfficeJet Pro 8020 series [72CF42] eSCL network scanner
I was able to scan a document using scanimage.
The actual model used to test is a 8028, which is the Costco version of the printer.  However, it looks as though 8020, 8022, 8023, 8024, 8025, 8026, 8028 are the currently produced sub-models under the 8020 series and one would assume all of these 802**x** models would work just the same.

README: Add HP OfficeJet Pro 8020 Series as a Supported eSCL Device

---

meson.build

Adds the inifile and init .c files to meson.build so that the meson
build doesn't fail with undefined symbol errors at link-time.

Add new .c files to meson.build

---

Makefile

```gcc -o test-zeroconf test-zeroconf.c -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic  -D_REENTRANT  -I/usr/include/libxml2  -I/usr/include/p11-kit-1    -I/usr/include/libpng16 -fPIC objs//libairscan.a  -lavahi-common -lavahi-client  -lxml2  -lgnutls -lm -fPIE  -ljpeg  -lpng16 -lz
/usr/bin/x86_64-openmandriva-linux-gnu-ld: objs//libairscan.a(airscan-eloop.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5' …
```

Link libpthread (minor fix)

---

README.md

I merged the two DCP-L2550D* in one line as they're very likely quite similar models, at least in terms of scanning.

Mark Brother DCP-L2550DN as tested in eSCL mode

---

airscan-mdns.c

clang 11 adds a new on-by-default diagnostic for casting a void pointer
to a smaller integer type (-Wvoid-pointer-to-enum-cast).  This causes a
warning in mdns_avahi_browser_callback when casting the userdata void
pointer to an MDNS_SERVICE value.  The warning is a false positive
because userdata is always passed as a value from the MDNS_SERVICE enum,
so we can cast it through intptr_t to eliminate the warning.

Suppress clang false positive warning

---

airscan-http.c
airscan-log.c

Adding fuzzing for http_query found two issues:
1. Passing a 0-length request body to http_query_new leaks memory
2. A very long log message can cause an out-of-bounds read in
log_message, because of a tricky detail about the return value of
vsnprintf().
This fixes both issues.

fix issues found from fuzzing http_query_*

---

FUZZER.md
fuzzer/query.cc
fuzzer/uri.cc
fuzzer/xml.cc
meson.build

This probably isn't ready to merge, but I wanted to send it for discussion as promised in #88.  I've only added the targets to meson for now.  If you like the general concept, we can do a more thorough job.
The basic idea is to fuzz functions that might process untrusted data.  The fuzzer uses code coverage information to generate inputs that gradually exercise more and more code paths.  It emits a reproduction case whenever it finds a crash or an asan failure. 
We want to start at high-level functions so that functions get called in the same way the code uses them, but we also don't want the fuzzer to trigger side effects or failures caused by external setup.  I've used functions defined in airscan.h as a heuristic for things that are likely to be around that level.  I didn't attempt to …

RFC: Add demonstration fuzzers

---

fuzzer/query.cc
fuzzer/uri.cc
fuzzer/xml.cc

The LICENSE file mentioned in fuzzer headers was meant to refer to the
main sane-airscan license, not a potentially separate fuzzer license.
Fixes #100.

Clarify fuzzer license

---

Makefile

This solves a reproducible builds issue: https://reproducible.archlinux.org/api/v0/builds/3156/diffoscope
```
│ ├── usr/share/man/man1/airscan-discover.1.gz
│ │ ├── filetype from file(1)
│ │ │ @@ -1 +1 @@
│ │ │ -gzip compressed data, was "airscan-discover.1", last modified: Mon Nov 23 21:29:37 2020, from Unix
│ │ │ +gzip compressed data, was "airscan-discover.1", last modified: Fri Nov 27 14:04:42 2020, from Unix
│ ├── usr/share/man/man5/sane-airscan.5.gz
│ │ ├── filetype from file(1)
│ │ │ @@ -1 +1 @@
│ │ │ -gzip compressed data, was "sane-airscan.5", last modified: Mon Nov 23 21:29:37 2020, from Unix
│ │ │ +gzip compressed data, was "sane-airscan.5", last modified: Fri Nov 27 14:04:42 2020, from Unix
```

Compress without embedded timestamps

---

airscan.conf

Those lines looks like examples, so let's comment them out to prevent problems with Xerox and HP device discovery :) .

airscan.conf: comment out lines from blacklist

---

README.md

Output of `scanimage -L`:
```
device `escl:https://192.168.1.102:443' is a HP OfficeJet Pro 7740 series [BBAE2F] platen,adf scanner
device `airscan:e0:HP OfficeJet Pro 7740 series [BBAE2F]' is a eSCL HP OfficeJet Pro 7740 series [BBAE2F] ip=192.168.1.102
```
I didn't test WSD as it wasn't displayed, so I assume it's not supported either.

Add HP OfficeJet Pro 7740

---

README.md

From #134 :
> To test with WSD, you need to set `protocol = manual` in the `/etc/sane.d/airscan.conf`. By default, all entries corresponding to the same physical device are merged and protocol is chosen automatically, so in the default configuration you will see only one device/protocol in the list (eSCL is preferred over WSD if both are available)
I tested with `scanimage -L` with the changed configuration and had the same output (no entry other than eSCL).

HP OfficeJet 7740 Pro:  Document no WSD support

---

airscan-escl.c
airscan-http.c
airscan.h

Some devices rely on finding the port in the Host HTTP header to
construct their response to the /eSCL/ScanJobs request.  When the port
isn't included, the steps up to the scan job creation work, but an
invalid redirect will be sent in the response to /eSCL/ScanJobs and then
the scan job will never finish.
Add a new quirk that forces the port to always be included in the Host
header.  This is known to affect some Epson models, and Epson has
indicated that this should be safe to use with all of their devices, so
enable it for eSCL whenever the manufacturer is Epson.  The quirk itself
is generic so that it can easily be enabled for more devices in the
future if needed.
Tested on a ET-3750.
Fixes #136.

Add quirk to force port in Host header

---

airscan-trace.c

GCC 11 with -Werror generates an error for 'strcpy' usage, so checking
the size and returning NULL if lesser than 4 works it around.

airscan-trace.c: Check the path length

---

airscan-devops.c
airscan-escl.c
airscan-id.c
airscan-wsd.c
airscan.c
airscan.h

Some scanners specify a justification parameter for ADF scans. This
patch exposes the XJustification value as a read-only value.

Expose width justification option to sane-airscan

---

README.md

Running airscan-discover returns:
```
[devices]
Brother HL-L2380DW series = http://[<ipv6>]:80/WebServices/ScannerService, WSD
Brother HL-L2380DW series = http://<ipv4>:80/WebServices/ScannerService, WSD
Brother HL-L2380DW series = http://[<ipv6>%254]:80/WebServices/ScannerService, WSD
```
Manually adding WSD and eSCL modes to /etc/sane.d/airscan.conf verifies that eSCL mode does not work and WSD mode works.  Leaving airscan.conf blank also works - WSD mode is automatically detected.

Add Brother HL-L2380DW series

---

README.md

airscan-discover
[devices]
Brother DCP-7055W = http://192.168.0.15:80/WebServices/ScannerService, WSD
Nothing with "avahi-browse -rt _uscan._tcp" or "avahi-browse -rt _uscans._tcp"

Add Brother DCP-7055W

---

README.md

I have one at home, here's what `scanimage -L` says:
```
device `airscan:w0:Brother DCP-J552DW' is a WSD Brother DCP-J552DW 
```
The best part is it actually works! Thanks for this software :heart:

Added Brother DCP-J552DW

---

README.md

Connected over network. Only WSD shows up so only entering that in the table for now.
```sh
>airscan-discover
[devices]
CANON INC. TS8230 series = http://10.9.8.249:80/wsd/scanservice.cgi, WSD
```

Add Canon TS8230

---

README.md

I tested scanning with my Xerox WorkCentre 6515 using WSD mode and it worked like a charm. Thus, adding this info to the table. I didn't test AirPrint since I disabled it on my device.
I also can no longer remember if WSD was disabled by default, so I didn't copy the footnote from the Xerox WorkCentre 6027.

Add Xerox WorkCentre 6515

---

meson.build

Fix for:
```
/usr/bin/ld: /tmp/ccGyngZO.ltrans2.ltrans.o: in function `sane_read':
sane-airscan-d9f2fd670dcb81c03fea7087fb9b47cdbe680fd5/redhat-linux-build/../airscan-device.c:1520: undefined reference to `image_format_detect'
```
Btw, any chance for a new releases? The last one is from 2021. Even if the master branch does not contain anything significant, releases are cheap.
Thanks,
--Simone

Fix Meson build - airscan-device.c:1520: undefined reference to 'image_format_detect'

---

README.md

Add HP Color Laser MFP M178nw - verified to be working as eSCL device on Fedora 39.

Add HP Color Laser MFP M178nw

---

README.md

Added (and tested):
- Brother DCP-7070DW
- Brother MFC-T910DW
- EPSON L6570 Series

added Brother and Epson scanners

---

README.md

At the very least simple scans work fine.
```
>airscan-discover
[devices]
Brother MFC-L3780CDW series = http://10.9.8.245:80/WebServices/ScannerService, WSD
```

docs: add Brother MFC-L3780CDW

---

README.md
airscan-wsd.c

Some devices don't behave if sca:ImagesToTransfer isn't set as expected.
Behaviour according to specification:
- single image to scan, ImagesToTransfer = 1 as for Flatbed
- multiple or unknown amount of images to scan, ImagesToTransfer = 0 as for ADF
Known devices affected:
- OKI MC332dn
- OKI MC362dn
- OKI MB471
Only relevant for WSD.

Address ImagesToTransfer behaviour

---

airscan-device.c
airscan-devops.c
airscan-escl.c
airscan-id.c
airscan-wsd.c
airscan.h

**WSD: Add content type selection**
Handle the WSD device settings element `ContentTypesSupported`, present its values as an option, and pass the selection to the scan job as `ContentType`.
The actual identifiers in code are made to match eSCL's "scan intent" setting, except for content type values exclusive to WSD. The setting is presented as `airscan-scan-intent`.
On some devices, this setting affects how colour is processed, and the default mode when not specified can result in inaccurate colours.
**eSCL: Add scan intent selection**
---
I reference this option from https://learn.microsoft.com/en-us/windows-hardware/drivers/image/contenttypevalue and https://learn.microsoft.com/en-us/windows-hardware/drivers/image/contenttype . The Canon PIXMA TR4570 I tested with supports "Text" and …

Add scan intent / WSD content type selection

---

airscan-devcaps.c
airscan-device.c
airscan-devops.c
airscan-escl.c
airscan-id.c
airscan-wsd.c
airscan.h

Both eSCL and WSD contains a very similar parameter, called `Intent` in the **eSCL** and `ContentType` in the **WSD**, which hints the scanner on the purpose of the scan request, letting scanner to choose optimal scan parameters.
`Intent` is documented in the Mopria eSCL Scan Specification, chapter 5 (https://mopria.org/mopria-escl-specification).
`ContentType` is documented by Microsoft here (https://learn.microsoft.com/en-us/windows-hardware/drivers/image/contenttypevalue) and here (https://learn.microsoft.com/en-us/windows-hardware/drivers/image/contenttype).
This patch (mostly contributed by @alvinhochun and polished by me), brings the uniform, protocol-independent access to this parameter into the set of scanner options, supported by `sane-airscan`

Merge scan-intent parameter support into the main branch

---

README.md

Tested Brother ADS-4300N scanner on Arch Linux, connected over network and over USB via ipp-usb. Multi-page documents and double-sided scanning works as expected over both network and USB.
```
$ airscan-discover
airscan-discover 
[devices]
Brother ADS-4300N [000EC69484E2] = http://[fe80::20e:c6ff:fe94:84e2%252]:8080/eSCL/, eSCL
Brother ADS-4300N [000EC69484E2] = https://[fe80::20e:c6ff:fe94:84e2%252]:443/eSCL/, eSCL
Brother ADS-4300N [000EC69484E2] = http://192.168.1.27:8080/eSCL/, eSCL
Brother ADS-4300N [000EC69484E2] = https://192.168.1.27:443/eSCL/, eSCL
Brother ADS-4300N [000EC69484E2] = http://[fe80::20e:c6ff:fe94:84e2%252]:53048, WSD
Brother ADS-4300N [000EC69484E2] = http://192.168.1.27:53048, WSD
```
```
$ airscan-discover
[devices]
Brother ADS-4300N (USB) = …
```

docs: Add Brother ADS-4300N

---

airscan-conf.c
airscan.c
airscan.conf
airscan.h
sane-airscan.5
sane-airscan.5.md

Scanners discovered by sane-airscan cannot be exported by saned, as the latter only operates on locally attached devices. This prevents some entirely reasonable use cases, as it is a bit ambiguous what locality even means in the context of scanners that only have an eSCL/WSD interface. The new "pretend-local" configuration option allows an administrator to set a policy that overrides the default behavior and makes these devices compatible with the SANE daemon.

Added the "pretend-local" config option for networked scanners to be treated as if attached locally

---

airscan-escl.c

This may be opinionated, but I would claim it's in practice better than the default. :-) I didn't dig far enough into SANE to understand if this can be exposed as an option; in any case, I'd argue it's even a _better default_.
1. Previously the format preference order was PNG, JPEG, TIFF, BMP; choose the first one that the scanner supports. Change it to PNG, TIFF, BMP, JPEG. Rationale: JPEG is almost certainly lossy. TIFF and BMP can be lossless. (Hmm, is there a lossy BMP?)
Now, it turns out my scanner, ET-8550, only offers to produce JPEG and PDF, so this part is... actually untested for effect. Dropping it would be fair, or I can put it in a separate PR if you prefer. At least it doesn't break anything for me.
2. The scanner reports the compression levels it supports. eSCL defines …

Statically choose lowest (least lossy) compression for JPEG and TIFF

---

README.md

WSD is detected and works. eSCL is not detected by airscan-discover(1).

Add EPSON EW-M752T to support list
